CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT,
	CUSTOMER_NAME VARCHAR(20),
	CUSTOMER_COUNTRY VARCHAR(15)
	
);

INSERT INTO CUSTOMERS
	VALUES(100, 'Jane', 'USA');
INSERT INTO CUSTOMERS
	VALUES(101, 'Bob', 'UK');
INSERT INTO CUSTOMERS
	VALUES(102, 'Miles', 'UK');