CREATE TABLE DISTINCT_ORDERS AS(
SELECT DISTINCT ORDER_ID,
                ORDER_STATUS,
                LAST_UPDATED
FROM ORDERS_DUPLICATE);

TRUNCATE TABLE ORDERS_DUPLICATE;

INSERT INTO ORDERS_DUPLICATE
SELECT * FROM  DISTINCT_ORDERS; 

DROP TABLE DISTINCT_ORDERS; 



