CREATE TABLE DISTINCT_ORDERS_2 AS(  --PLACEHOLDER TABLE
SELECT 
	ORDER_ID,
	ORDER_STATUS,
	LAST_UPDATED,
	ROW_NUMBER() OVER(PARTITION BY ORDER_ID, ORDER_STATUS, LAST_UPDATED) 	DUP_COUNT
FROM ORDERS_DUPLICATE -- NAME OF TABLE THAT HAS DUPLICATE VALUES
	
);

TRUNCATE TABLE ORDERS_DUPLICATE;  -- CLEARS ALL THE CONTENT OF THE ORIGINAL TABLE

INSERT INTO ORDERS_DUPLICATE(  -- AGAIN, THE NAME OF THE ORGINAL TABLE THAT HAS DUPLICATES BY THE END, THE VALUES WILL BE DISTINCT AFTER INSERTING DISTINCT VALUES FROM PLACEHOLDER TABLE
SELECT 
	ORDER_ID,
	ORDER_STATUS,
	LAST_UPDATED
FROM DISTINCT_ORDERS_2
WHERE DUP_COUNT =1 
);

DROP TABLE DISTINCT_ORDERS_2;  -- DROPS PLACEHOLDER TABLE