CREATE TABLE DISTINCT_ORDERS AS(    -- PLACEHOLDER TABLE
SELECT DISTINCT ORDER_ID,
                ORDER_STATUS,
                LAST_UPDATED
FROM ORDERS_DUPLICATE);  -- NAME OF TABLE THAT HAS DUPLICATE VALUES

TRUNCATE TABLE ORDERS_DUPLICATE;  -- CLEARS ALL THE CONTENT OF THE ORIGINAL TABLE

INSERT INTO ORDERS_DUPLICATE   -- AGAIN, THE NAME OF THE ORGINAL TABLE THAT HAS DUPLICATES BY THE END, THE VALUES WILL BE DISTINCT AFTER INSERTING DISTINCT VALUES FROM PLACEHOLDER TABLE
SELECT * FROM  DISTINCT_ORDERS; 

DROP TABLE DISTINCT_ORDERS;   -- DROPS PLACEHOLDER TABLE



