CREATE TABLE IF NOT EXISTS ORDER_SUMMARY_DAILY(
    ORDER_DATE          DATE,
    ORDER_COUNTRY       VAR_CHAR(10),
    TOTAL_REVENUE       NUMRIC,
    ORDER_COUNT         INT


);


INSERT INTO ORDER_SUMMARY_DAILY
(ORDER_DATE, ORDER_COUNTRY, TOTAL_REVENUE, ORDER_COUNT)
SELECT  
    O.ORDER_DATE,
    C.CUSTOMER_COUNTRY,
    SUM(ORDER_TOTAL)    TOTAL_REVENUE,
    COUNT(O.ORDER_ID)   ORDER_COUNT
FROM ORDERS             O
INNER JOIN CUSTOMERS    C
    ON C.CUSTOMER_ID    =   O.CUSTOMER_ID
GROUP BY 
    O.ORDER_DATE,
    C.CUSTOMER_COUNTRY